### PR TITLE
Support initialization from SimpleXMLELement object ++

### PR DESCRIPTION
**Pull request by danmichaelo**
Sometimes you happen to already have a SimpleXMLELement object, such as when you harvest records from OAI-PMH using [caseyamcl/phpoaipmh](https://github.com/caseyamcl/phpoaipmh). Until now I have just serialized the XML before passing it to File_MARC, but serialization and parsing of large XML files can be a somewhat expensive operation.

While my original intention was to just add SimpleXMLELement support, I couldn't get tests running with phpunit, so I ended up doing a few more changes…

1. d8fc579 fixes a general autoloading issue.
2. d9cfacd makes the tests run under Phpunit.
3. 89d13ba changes `.travis.yml` to also test using Composer+PHPUnit (and adds PHP 7.1 and 7.2)
4. 667beb6 actually adds support for constructing a File_MARCXML object from a SimpleXMLELement object.
5. b7bde9e fixes the static calls to non-static methods in validate/ispn (The library itself used static calls before, but no longer: https://github.com/pear/Validate_ISPN/pull/2)

### CODE REVIEW

**Comment by dbs** [comment]
@danmichaelo I don't use File_MARC regularly and don't have time to review changes of this magnitude. Would you be interested in taking over ownership of this PEAR package?

**Comment by danmichaelo** [comment]
Hm, I could.. but in that case I would prefer to move away from Pear completely since maintaining Pear support is quite expensive timewise. Do you know if there's any other Pear packages that depends on File_MARC, or any other strong reason to keep Pear support?

**Comment by dbs** [comment]
It seems there are people or scripts who still install via "pear install File_MARC" even though packagist/composer is the current hotness. http://pear.php.net/package-stats.php?pid=662&cid=33 says there have been 19 downloads via PEAR since the last release a few days ago, and almost 1,300 for the previous release in January (even if you cut that in half to reflect automated downloads, that's still a lot).

I would hate to leave them behind.

**Comment by danmichaelo** [comment]
I see. And as long as it also works with Composer and with the latest PHP version, there is no pressing need to remove it.. But I'm a bit hesitant to learn a package system that's mostly dead :/ Do you think you could keep doing the releases? I could still help out as a maintainer on GitHub. We could also promote composer as an installation method – right now it's not mentioned in the README :)

Btw. most of the changes in this PR is bootstrapping for the tests. If you look away from that, this is a very small change :) https://github.com/pear/File_MARC/commit/667beb6eb1f5af9d9b85038a5b7aa94d46ce349b

**Comment by CloCkWeRX** [comment]
@dbs - would you be happy with @danmichaelo's offer to help maintain? If so, can set that up.

**Pull request merged**
